const yarnInMyCloset = [
	{
		id: 1,
		name: 'Cakes',
		brand: 'Caron',
		material: 'blend (acrylic-wool)',
		color: 'multi',
		yarn_weight: 'worsted',
		quantity: 2,
		partials: true,
	},
	{
		id: 2,
		name: 'Sugar \'N Cream',
		brand: 'Lily',
		material: 'cotton',
		color: 'purple',
		yarn_weight: 'worsted',
		quantity: 3,
		partials: true,
	},
	{
		id: 3,
		name: 'Grace',
		brand: 'Patons',
		material: 'cotton (mercerized)',
		color: 'green',
		yarn_weight: 'sport',
		quantity: 3,
		partials: false,
	},
	{
		id: 4,
		name: 'Kroy Socks',
		brand: 'Patons',
		material: 'blend (wool-nylon)',
		color: 'pink-multi',
		yarn_weight: 'super-fine',
		quantity: 2,
		partials: true,
	},
	{
		id: 5,
		name: 'Wool-Ease',
		brand: 'Lion',
		material: 'blend (acrylic-wool)',
		color: 'brown',
		yarn_weight: 'worsted',
		quantity: 1,
		partials: false,
	},
	{
		id: 6,
		name: 'Classic Wool',
		brand: 'Patons',
		material: 'wool',
		color: 'gray',
		yarn_weight: 'worsted',
		quantity: 4,
		partials: true,
	},
];

module.exports = {
	yarnInMyCloset
}